### ISSUE TITLE
.pth installation does not work

### ISSUE THREAD

**Issue by asottile** [georgek42/inlinec#1]
After installing into a virtualenv at `/tmp/x/venv` I get the `.pth` file at this location:

```console
$ find venv -name "*.pth"
venv/lib/python3.6/site-packages/tmp/x/venv/lib/python3.6/site-packages/inlinec.pth
```

you may find [this prior art](https://github.com/asottile/future-fstrings/blob/master/setup.py) helpful ;)

**Comment by ssize-t** [comment]
Oh, this is great! Thanks!

Very helpful indeed :)
