### ISSUE TITLE
Proper documentation on how to run it.

### ISSUE THREAD

**Issue by gnuille** [georgek42/inlinec#2]
I successfully installed the docker image and tried to run the example in the documentaiton.

```bash
python3.8 test.py
```
Outputs:
```
  File "test.py", line 5
    float Q_rsqrt( float number )
          ^
SyntaxError: invalid syntax
```
I may be not running in a proper way but i would like to know how to run altough I can not find anything on this topic.

I'm sorry if tt's clearly written somewhere but I can't find it.
Thanks.

**Comment by ssize-t** [comment]
Make sure to have the `# coding: inlinec` comment on the first or second line of the file.

This should definitely be documented better. Good point
Thanks!

**Comment by EkremDincel** [comment]
Now I am getting this error:
````
unknown encoding: inlicec
````
But I installed inlinec, this code works fine:
````python
from inlinec import inlinec
````

**Comment by ssize-t** [comment]
@EkremDincel Looks like you have a typo in the coding comment — “inlicec” should be “Inlinec”

**Comment by gnuille** [comment]
Thanks for everything. Now I have my code running better than I expected :)

**Comment by asukaminato0721** [comment]
The same problem

py 3.8.5

![image](https://user-images.githubusercontent.com/30024051/96014605-2769aa00-0e79-11eb-85cd-8a2ddb32dd70.png)

Code is copied from readme.md
